server:
  port: ${PORT:${SERVER_PORT:0}}
 # port: 8082
spring:
  application:
    name: api-playlist
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spotify-dev
    username: root
    password: 127465211q
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/